name: 'house_price_data'
profile: 'house_price_data'
config-version: 2
version: '0.0.1'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

seeds:
  house_price_data:
    schema: seeds

models:
  house_price_data:
    schema: house_price_data